[[qpOASES]]
arch = "aarch64"
git-tree-sha1 = "25719d6b4a489ba2e24ff9039004e6704fb761ee"
os = "macos"

    [[qpOASES.download]]
    sha256 = "2db1f880218d9fa73d95ef63981a2aeca19bedc3837c66473b1f507741aa18cb"
    url = "https://github.com/JuliaBinaryWrappers/qpOASES_jll.jl/releases/download/qpOASES-v3.2.2+0/qpOASES.v3.2.2.aarch64-apple-darwin.tar.gz"
[[qpOASES]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9eaef19903f59b7f0adfe539520d89ab03af0038"
libc = "glibc"
os = "linux"

    [[qpOASES.download]]
    sha256 = "e19a35f4450bffa48b8679b1dee2a8ecbf8c17b2ba6be3cd403e6aeda92a6346"
    url = "https://github.com/JuliaBinaryWrappers/qpOASES_jll.jl/releases/download/qpOASES-v3.2.2+0/qpOASES.v3.2.2.aarch64-linux-gnu-cxx03.tar.gz"
[[qpOASES]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53440a9424e2bc06eb90a06371edf2c91bb50e94"
libc = "glibc"
os = "linux"

    [[qpOASES.download]]
    sha256 = "44ec76a414ef6951fbf28be205d20d074f9149f644737db2ccaef1b9147db2d3"
    url = "https://github.com/JuliaBinaryWrappers/qpOASES_jll.jl/releases/download/qpOASES-v3.2.2+0/qpOASES.v3.2.2.aarch64-linux-gnu-cxx11.tar.gz"
[[qpOASES]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "31f2351ba81e3b1f8b7e96a0f1e6c1b4dc027339"
libc = "glibc"
os = "linux"

    [[qpOASES.download]]
    sha256 = "badfbb91b91d1e4a437dbd5cea9580309815687fccef35ee073d5e7478e73904"
    url = "https://github.com/JuliaBinaryWrappers/qpOASES_jll.jl/releases/download/qpOASES-v3.2.2+0/qpOASES.v3.2.2.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[qpOASES]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "270213e57b45da1f70ced198b670dfbbf1b0a7ab"
libc = "glibc"
os = "linux"

    [[qpOASES.download]]
    sha256 = "334fab60eab9a066af5e47868cd81a12918d42e7c55c09d7aea4ead02b5fe7de"
    url = "https://github.com/JuliaBinaryWrappers/qpOASES_jll.jl/releases/download/qpOASES-v3.2.2+0/qpOASES.v3.2.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[qpOASES]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5a020cc9a3865cd88f3f0a139c9b21fbf690767"
libc = "glibc"
os = "linux"

    [[qpOASES.download]]
    sha256 = "1dfdee93347e881f5cb352e7b07e2e6ae0fdf030a505b97c05a9d26e9240bc0f"
    url = "https://github.com/JuliaBinaryWrappers/qpOASES_jll.jl/releases/download/qpOASES-v3.2.2+0/qpOASES.v3.2.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[qpOASES]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24703ab62ae46f50f83771cb57e685ab5ae20563"
libc = "glibc"
os = "linux"

    [[qpOASES.download]]
    sha256 = "c0ddeb952c4273afa697bad9eaa5751600542018d46f5520979908d8ba01f119"
    url = "https://github.com/JuliaBinaryWrappers/qpOASES_jll.jl/releases/download/qpOASES-v3.2.2+0/qpOASES.v3.2.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[qpOASES]]
arch = "x86_64"
git-tree-sha1 = "c719bc379eb3fe1d9646bfec259d1543f1b4109a"
os = "macos"

    [[qpOASES.download]]
    sha256 = "438c39ae82a33160fceec47cc1897178145a3d93c70b98981cc3cad13a30d275"
    url = "https://github.com/JuliaBinaryWrappers/qpOASES_jll.jl/releases/download/qpOASES-v3.2.2+0/qpOASES.v3.2.2.x86_64-apple-darwin.tar.gz"
[[qpOASES]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f73c37b3f9ca57f648d1043a96f073e03a567b9a"
libc = "glibc"
os = "linux"

    [[qpOASES.download]]
    sha256 = "6f12cdad74205c400575f94c1d23de5e6e4499ba6f79f6f60303c37f8832e4ef"
    url = "https://github.com/JuliaBinaryWrappers/qpOASES_jll.jl/releases/download/qpOASES-v3.2.2+0/qpOASES.v3.2.2.x86_64-linux-gnu-cxx03.tar.gz"
[[qpOASES]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "750e02ba720eba8c8b38903ba8cf3dbc21f0ca24"
libc = "glibc"
os = "linux"

    [[qpOASES.download]]
    sha256 = "91e526a78c07445417e81a2a55743a43ca1297773391cd125027f07ed2937572"
    url = "https://github.com/JuliaBinaryWrappers/qpOASES_jll.jl/releases/download/qpOASES-v3.2.2+0/qpOASES.v3.2.2.x86_64-linux-gnu-cxx11.tar.gz"
[[qpOASES]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c36c19e509746dc64a152aa7d8be0bed440726cf"
os = "windows"

    [[qpOASES.download]]
    sha256 = "aed324004da65b3e11ef759c088df530b7e020da0bcaa31147b1d13f6002e603"
    url = "https://github.com/JuliaBinaryWrappers/qpOASES_jll.jl/releases/download/qpOASES-v3.2.2+0/qpOASES.v3.2.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[qpOASES]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a9cbbf3a5f6ea79069a32606147bace726aa23c9"
os = "windows"

    [[qpOASES.download]]
    sha256 = "b4524e6d305c825efcc054e9e2e3ac96fb2f10771654010d093244618733bd15"
    url = "https://github.com/JuliaBinaryWrappers/qpOASES_jll.jl/releases/download/qpOASES-v3.2.2+0/qpOASES.v3.2.2.x86_64-w64-mingw32-cxx11.tar.gz"
